// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzgmgasacltuphvqfwzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16Z21nYXNhY2x0dXBodnFmd3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDA2NTgsImV4cCI6MjA2MTY3NjY1OH0.yRRy9_9LSabBPYPh2Y9a5U5zhzq7aEKXR-hatPXXFeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);